# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: test

steps:
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'http://192.168.11.46:9090/scancentral-ctrl'
    scanCentralClientToken: 'admin123!'
    sscUrl: 'http://192.168.11.53:8081/ssc'
    sscCiToken: 'YTk4NTQ2MDctMzliMC00MDk2LTkyNDUtOTVhOWM2ZTAyNjY4'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '10005'
    autoDetectBuildTool: true
